apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k8s-mqtt-subscriber
  name: k8s-mqtt-subscriber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-mqtt-subscriber
  template:
    metadata:
      labels:
        app: k8s-mqtt-subscriber
    spec:
      containers:
      - image: pserpaschiavo/k8s-mqtt-subscriber:1.0
        name: k8s-mqtt-subscriber
        # command:
        # - "sleep"
        # - "604800"
        imagePullPolicy: Always
        ports:
        - containerPort: 1883
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"