apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k8s-mqtt-publisher
  name: k8s-mqtt-publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-mqtt-publisher
  strategy: {}
  template:
    metadata:
      labels:
        app: k8s-mqtt-publisher
    spec:
      containers:
      - image: pserpaschiavo/k8s-mqtt-publisher:1.0
        name: k8s-mqtt-publisher
        command:
        - "sleep"
        - "604800"
        ports:
        - containerPort: 1883
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "1"